server {
    listen 80;
    server_name localhost;

    # Serve React Frontend
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Match the relative /api/auth path from userService
    location /api/auth/ {
        proxy_pass http://auth-server:4000/; # Trailing slash strips /api/auth/ when sending to backend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Match the relative /api/notes path from noteService
    location /api/notes/ {
        proxy_pass http://notes-server:5000/api/; # Maps perfectly to your Flask backend route structure
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}